config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root to: "dashboard#index"

    resources :votings
    resources :users
    resources :groups
  end

  namespace :users do
    root to: "dashboard#index"

    resource :invitation_password, only: [:edit, :update]
    resources :submits, only: [:index, :show, :edit, :update]
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/views/layouts/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" 
        class="navbar-toggle collapsed" 
        data-toggle="collapse" 
        data-target="#bs-example-navbar-collapse-1" 
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if admin_signed_in? %>
        <%= link_to Settings.service_name, admins_root_path, class: 'navbar-brand navbar-brand-center' %>
      <% elsif user_signed_in? %>
        <%= link_to Settings.service_name, users_root_path, class: 'navbar-brand navbar-brand-center' %>
      <% else %>
        <%= link_to Settings.service_name, users_root_path, class: 'navbar-brand navbar-brand-center' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- メニュー追加サンプル
      <ul class="nav navbar-nav">
        <li><a href='#'>menu1</a></li>
        <li class='active'><a href='#'>menu2</a></li>
      </ul>
      -->
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a href="#" 
              class="dropdown-toggle" 
              data-toggle="dropdown" 
              role="button" 
              aria-haspopup="true" 
              aria-expanded="false"><%= Admin.model_name.human %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to(t('views.link.logout'), destroy_admin_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% elsif user_signed_in? %>
          <li class="dropdown">
            <a href="#" 
              class="dropdown-toggle" 
              data-toggle="dropdown" 
              role="button" 
              aria-haspopup="true" 
              aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to(t('views.link.logout'), destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to(t('views.link.login'), new_user_session_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>