config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root to: "dashboard#index"

    resources :votings
    resources :users
    resources :groups
  end

  namespace :users do
    root to: "dashboard#index"

    resource :invitation_password, only: [:edit, :update]
    resources :submits, only: [:index, :show, :edit, :update]
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enumerize :status, in: %i(inviting registrated)

  before_save :set_tmp_password

  has_many :submits, dependent: :destroy

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups

  validates :name, presence: true

  # 仮パスワードの削除
  def delete_temp_password
    self.update(temp_password: nil)
  end

  # 仮パスワードを一旦本番パスワードに入れる
  def build_password
    self.password = self.temp_password
    self.password_confirmation = self.temp_password
  end

  private

  def set_tmp_password
    self.temp_password = password
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: %w(edit update, destroy)

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.build_password
    if  @user.save
      redirect_to admins_users_url, notice: t('.admins.users.notice')
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: t(".admins.users.notice")
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admins_users_url, notice: t(".admins.users.notice")
    else 
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name, 
      :email,
      :temp_password
    )
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end
  #

  # POST /resource/confirmation
  # def create
  #   super
  # end
  #

  # GET /resource/confirmation?confirmation_token=abcdef
  #def show
  #  super
  #end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
  #
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/invitation_passwords_controller.rb
class Users::InvitationPasswordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %w(edit update)

  def update
    @user.password_updated_at = DateTime.now
    if @user.update(user_params)
      sign_in(@user, bypass: true) if current_user.id == @user.id
      redirect_to users_root_path, notice: t('.users.invitation_passwords.notice')
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
      :password, 
      :password_confirmation
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  # protected

  def after_resetting_password_path_for(resource)
    users_root_path
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]
  
  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  #

  def after_sign_in_path_for(resource)
    if resource.password_updated_at
      users_root_path
    else
      edit_users_invitation_password_path
    end
  end

  def after_sign_out_path_for(resource)
    user_session_path
  end

end

app/controllers/users/submits_controller.rb
class Users::SubmitsController < ApplicationController
  before_action :authenticate_user!
  before_action :submit_params, only: %w(update)

  def index
    @submits = current_user.submits.order('created_at desc')
  end

  def show
  end

  def edit
    @submit = current_user.submits.find(params[:id])

    if @submit.submited_at.nil?
      render :edit
    else
      render :show
    end
  end

  def update
    @submit = current_user.submits.find(params[:id])
    @submit.submited_at = DateTime.now
    @submit.update(submit_params)
    redirect_to  users_submits_path, notice: t('.notice')
  end

  private

  def submit_params
    params.require(:submit).permit(
      :user_id,
      :voting_id,
      :delegater,
      decisions_attributes: [:id, :proposal_id, :decision]
    )
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admins/users/_form.html.erb
<%= error_message(@user) %>

<div class="form-group">
  <%= f.label :name, for: 'inputName', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :name, autofocus: true, class: 'form-control', id: 'inputName' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :email, for: 'inputEmail', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :email, class: 'form-control', id: 'inputEmail' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :temp_password, for: 'inputPassword', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :temp_password, class: 'form-control', id: 'inputPassword' %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit t('views.button.sent'), class: 'btn btn-primary' %>
  </div>
</div>

app/views/admins/users/index.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('dashboard'), admins_root_path %></li>
    <li><%= link_to t('.command.new'), new_admins_user_path %></li>
  </ul>
<% end %>

<div class="page-header">
  <h2><%= t('.title') %></h2>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <th><%= User.human_attribute_name(:status) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
    <tr>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.created_at.to_s(:Ymd) %></td>
      <td>
        <% if u.confirmed_at %>
          <%= User.status.registrated.text %>
        <% else %>
          <%= User.status.inviting.text %>
        <% end %>
      </td>
      <td>
        <%= link_to t('.link.edit'), edit_admins_user_path(u) %>
        <%= link_to t('.link.destroy'), admins_user_path(u), method: :delete, data: {confirm: '本当に削除しますか？'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/users/new.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('.command.index'), admins_users_path %></li>
  </ul>
<% end %>

<div class="page-header">
  <h2><%= t('.title') %></h2>
</div>

<%= form_for @user, url: admins_users_path, html: {class: 'form-horizontal'} do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>