config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root to: "dashboard#index"

    resources :votings
    resources :users
    resources :groups
  end

  namespace :users do
    root to: "dashboard#index"

    resource :invitation_password, only: [:edit, :update]
    resources :submits, only: [:index, :show, :edit, :update]
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/views/admins/shared/_command.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('dashboard'), admins_root_path %></li>
    <li><%= link_to t('votings'), admins_votings_path %></li>
    <li><%= link_to t('.users'), admins_users_path %></li>
    <li><%= link_to t('.groups'), admins_groups_path %></li>
  </ul>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('views.link.login'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('link.forget_password'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>