config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    root to: "dashboard#index"

    resources :votings
    resources :users
    resources :groups
  end

  namespace :users do
    root to: "dashboard#index"

    resource :invitation_password, only: [:edit, :update]
    resources :submits, only: [:index, :show, :edit, :update]
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/models/voting.rb
class Voting < ApplicationRecord
  has_many :proposals, dependent: :destroy
  accepts_nested_attributes_for :proposals, allow_destroy: true, reject_if: :valid_empty

  has_many :submits, dependent: :destroy
  accepts_nested_attributes_for :submits, allow_destroy: true

  validates :title, :description, presence: true

  def unsubmit_users
    self.submits.where(submited_at: nil).map(&:user)
  end

  private 

  #
  # proposalsのtitleとbodyがからのものは、削除フラグが立っていると同じ状況とみなす。
  #
  def valid_empty(attributes)
    if (attributes[:title].blank? && attributes[:body].blank?)
      attributes[:_destroy] = 1
    end
  end

end

app/controllers/admins/votings_controller.rb
class Admins::VotingsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_voting, only: %w(show edit update)

  def index
    @votings = Voting.all.order('created_at desc')
  end

  def new
    @voting = Voting.new
    @voting.proposals.build
    User.all.each { |u| @voting.submits.build(user_id: u.id) }

    @groups = Group.all
  end

  def create
    @voting = Voting.new(voting_params)

    # voting {proposals_attributes, submits_attributes} 作成
    # decision 手動作成(proposalがview側で動的作成なため、view側で定義するコストが高いため)
    ActiveRecord::Base.transaction do
      @voting.save
      @voting.submits.each do |s|
        @voting.proposals.each { |p| s.decisions.create(proposal_id: p.id) }
      end
    end
      @voting.submits.each { |s| s.send_invite_submittion_mail }
      redirect_to admins_votings_url, notice: t('.admins.votings.notice')
    rescue => e
      logger.fatal e.message
      logger.fatal e.backtrace.join("\n")
      redirect_to admins_votings_url, notice: t('.admins.votings.error')
  end

  private

  def set_voting
    @voting = Voting.find(params[:id])
  end

  def voting_params
    params.require(:voting).permit(
      :title, 
      :description,
      submits_attributes: [:user_id, :_destroy],
      proposals_attributes: [:id, :title, :body, :_destroy],
      submit_decisions_attributes: [:proposal_id]
    )
  end
end

app/helpers/voting_helper.rb
module VotingHelper
end

app/views/admins/votings/_form.html.erb
<%= javascript_include_tag 'admins/voting' %>

<%= error_message(@voting) %>

<div class="form-group">
  <%= f.label :title, for: 'inputTitle', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :title, autofocus: true, class: 'form-control', id: 'inputTitle' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :description, for: 'inputDescription', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_area :description, class: 'form-control', id: 'inputDescription', rows: 10 %>
  </div>
</div>

<div class='form-group'>
  <label for="checkUsers" class="col-sm-2 control-label"><%= Group.model_name.human %></label>
  <div class="col-sm-10">
    <% @groups.each do |g| %>
      <label><%= radio_button_tag 'group[id]', g.id, '', {class: 'groups-radio'} %>&nbsp;<%= g.name %>&nbsp;</label>
    <% end %>
    <label><input type='radio' id='groupUsersClear' name='group[id]' checked />&nbsp;<%= t('.label.group.none') %>&nbsp;</label>
  </div>
</div>

<div class='form-group'>
  <label for="checkUsers" class="col-sm-2 control-label"><%= User.model_name.human %></label>
  <div class="col-sm-10">
    <%= f.fields_for :submits do |s| %>
      <label><%= s.check_box :user_id, 
        {checked: false, class: 'voting-user-checkbox'}, 
        s.object.user.id, 
        0 %>&nbsp;<%= s.object.user.name %></label>
      &nbsp;
      <%= hidden_field_tag "voting[submits_attributes][#{s.index}][_destroy]", 1, 
        id: "voting_submits_attributes_#{s.index}__destroy" %>
    <% end %>
  </div>
</div>

<div class="page-header">
  <h4><center><%= Proposal.model_name.human %></center></h4>
</div>

<div id='proposals'>
  <%= f.fields_for :proposals do |p| %>
    <div class='proposal'>
      <div class="form-group">
        <%= p.label :title, for: 'inputTitle', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10"><%= p.text_field :title, class: 'form-control', id: 'inputTitle' %></div>
      </div>

      <div class="form-group">
        <%= p.label :body, for: 'inputBody', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10"><%= p.text_area :body, class: 'form-control', id: 'inputBody', rows: 10 %></div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label><%= p.check_box :_destroy %><%= f.label :_destroy %></label>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= link_to t('.button.add'), '#', onclick: 'add_proposal()', class: 'btn btn-default pull-right' %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <center>
      <%= f.submit t('views.button.sent'), class: 'btn btn-danger btn-lg' %>
    </center>
  </div>
</div>

app/views/admins/votings/edit.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('.command.index'), admins_votings_path %></li>
    <li><%= link_to t('.command.new'), new_admins_voting_path %></li>
  </ul>
<% end %>

<div class="page-header">
  <h2><%= t('.title') %></h2>
</div>

<%= form_for @voting, url: admins_voting_path, html: {class: 'form-horizontal'} do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/admins/votings/index.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('dashboard'), admins_root_path %></li>
    <li><%= link_to t('.command.new'), new_admins_voting_path %></li>
  </ul>
<% end %>

<div class="page-header">
  <h2><%= t('.title') %></h2>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= Voting.human_attribute_name(:title) %></th>
      <th><%= Voting.human_attribute_name(:created_at) %></th>
      <th>未提出者</th>
    </tr>
  </thead>
  <tbody>
    <% @votings.each do |v| %>
      <tr>
        <td><%= link_to v.title, admins_voting_path(v) %></td>
        <td><%= v.created_at.to_s(:Ymd) %></td>
        <td>
          <% v.unsubmit_users.each do |u| %>
            <%= u.name %>,&nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/votings/new.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('.command.index'), admins_votings_path %></li>
  </ul>
<% end %>

<div class="page-header">
  <h2><%= t('.title') %></h2>
</div>

<%= form_for @voting, url: admins_votings_path, html: {class: 'form-horizontal'} do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/admins/votings/show.html.erb
<% content_for :command do %>
  <ul class="nav nav-list">
    <li><%= link_to t('.command.index'), admins_votings_path %></li>
    <li><%= link_to t('.command.new'), new_admins_voting_path %></li>
    <!--<li><%= link_to t('.command.edit'), edit_admins_voting_path(@voting) %></li>-->
  </ul>
<% end %>

<div class="page-header">
  <h2><center><%= @voting.title %></center></h2>
</div>

<div><%= @voting.description %></div>

<div class="page-header">
  <h4><center><%= Proposal.model_name.human %></center></h4>
</div>
<% @voting.proposals.each do |p| %>
  <div class='well'>
    <div class="page-header">
      <h5><%= p.title %></h5>
      <p><%= p.body %></p>
      <table class='table'>
        <% Decision.decision.values.each do |d| %>
          <tr>
            <td><%= d.text %></td>
            <td><%= Decision.send("count_#{d}", p.id) %></td>
            <td>
              <%# Decision.send("users_#{d}", p.id).each do |u| %>
              <%# end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

<div class="page-header">
  <h4>サマリー</h4>
</div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= Proposal.human_attribute_name(:title) %></th>
      <% Decision.decision.values.each do |d| %>
        <th><%= Decision.decision.find_value(d).text %></th>
      <% end %>
    </tr>
  </thead>
  <% @voting.proposals.each do |p| %>
    <tr>
      <td width='200'><%= p.title %></td>
      <% Decision.decision.values.each do |d| %>
        <td><%= Decision.send("count_#{d}", p.id) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />
<br />
<div class="page-header">
  <h4><%= t('.delegate_description') %></h4>
</div>

<% @voting.submits.each do |s| %>
  <div class='well'>
    <div class="page-header">
      <h4>
        <%= s.user.name %> 
        <small>
          <%= Submit.human_attribute_name(:submited_at) %> : 
          <% if s.submited_at? %>
            <%= s.submited_at.to_s(:Ymd) %>
          <% else %>
            <label class='label label-danger'><%= t('.unsubmit') %></label>
          <% end %>
        </small>
      </h4>
    </div>
    <p><%= Submit.human_attribute_name(:delegater) %> : <%= s.delegater %></p>
    <table class='table table-striped'>
      <% s.decisions.each do |d| %>
        <tr>
          <td><%= d.proposal.title %></td>
          <td><%= Decision.decision.find_value(d.decision).text %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>